#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.8.2 on Thu May 31 17:20:47 2018
#

import wx
from spire_log_uploader import SpireLogUploader

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade

spire_uploader = SpireLogUploader()


class WrongConfig(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: WrongConfig.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetSize((400, 90))

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: WrongConfig.__set_properties
        self.SetTitle("Incorrect Config")
        self.SetSize((400, 90))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: WrongConfig.__do_layout
        wrong_config_sizer = wx.BoxSizer(wx.HORIZONTAL)
        wrong_config_label = wx.StaticText(self, wx.ID_ANY, "Your config file is setup incorrectly \ncausing Spire "
                                                            "Log Uploader to not function!", style=wx.ALIGN_CENTER)
        wrong_config_label.SetMinSize((400, 53))
        wrong_config_label.SetFont(wx.Font(14, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        wrong_config_sizer.Add(wrong_config_label, 0, wx.ALIGN_CENTER | wx.ALL | wx.EXPAND, 4)
        self.SetSizer(wrong_config_sizer)
        self.Layout()
        self.Centre()
        # end wxGlade

    def show_dialog(self):
        self.Show()
        self.SetFocus()

# end of class WrongConfig


class SpireUploaderFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SpireUploaderFrame.__init__
        kwds["style"] = kwds.get("style",
                                 0) | wx.CAPTION | wx.CLIP_CHILDREN | wx.CLOSE_BOX | wx.MINIMIZE_BOX | wx.SYSTEM_MENU
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((400, 170))
        self.spire_notebook = wx.Notebook(self, wx.ID_ANY)
        self.login_panel = wx.Panel(self.spire_notebook, wx.ID_ANY)
        self.username_textbox = wx.TextCtrl(self.login_panel, wx.ID_ANY, "")
        self.password_textbox = wx.TextCtrl(self.login_panel, wx.ID_ANY, "", style=wx.TE_PASSWORD)
        self.login_btn = wx.Button(self.login_panel, wx.ID_ANY, "Login")
        self.Bind(wx.EVT_BUTTON, self.login_btn_pressed, self.login_btn)
        self.upload_panel = wx.Panel(self.spire_notebook, wx.ID_ANY)
        self.upload_btn = wx.Button(self.upload_panel, wx.ID_ANY, "Upload All")
        self.Bind(wx.EVT_BUTTON, self.upload_btn_pressed, self.upload_btn)
        self.watch_btn = wx.Button(self.upload_panel, wx.ID_ANY, "Start Watching")
        self.Bind(wx.EVT_BUTTON, self.watch_btn_pressed, self.watch_btn)
        self.spire_frame_statusbar = self.CreateStatusBar(1)
        self.incorrect_config_dialog = WrongConfig(None, wx.ID_ANY, "")
        self.watching_folder = False

        self.__set_properties()
        self.__do_layout()

        # end wxGlade

    def login_btn_pressed(self, event):
        if not spire_uploader.config.correct_config():
            self.incorrect_config_dialog.show_dialog()
            return

        self.spire_frame_statusbar.SetStatusText('Logging in')
        if spire_uploader.login(self.username_textbox.GetValue(), self.password_textbox.GetValue()):
            self.spire_frame_statusbar.SetStatusText('Login successful')
        else:
            self.spire_frame_statusbar.SetStatusText('Login failed')

    def upload_btn_pressed(self, event):
        if not spire_uploader.config.correct_config():
            self.incorrect_config_dialog.show_dialog()
            return
        spire_uploader.upload_all()

    def watch_btn_pressed(self, event):
        if not spire_uploader.config.correct_config():
            self.incorrect_config_dialog.show_dialog()
            return
        if self.watching_folder:
            spire_uploader.stop_watch()
            self.watching_folder = False
            self.watch_btn.SetLabel('Start watching')
        else:
            spire_uploader.start_watch()
            self.watching_folder = True
            self.watch_btn.SetLabel('Stop watching')

    def __set_properties(self):
        # begin wxGlade: SpireUploaderFrame.__set_properties
        self.SetTitle("SpireLog Uploader")
        self.login_panel.SetMinSize((376, 100))
        self.spire_frame_statusbar.SetStatusWidths([-1])

        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: SpireUploaderFrame.__do_layout
        main_sizer = wx.BoxSizer(wx.VERTICAL)
        login_sizer = wx.BoxSizer(wx.HORIZONTAL)
        login_grid_sizer = wx.FlexGridSizer(0, 1, 5, 0)
        username_sizer = wx.FlexGridSizer(0, 2, 0, 5)
        password_sizer = wx.FlexGridSizer(0, 2, 0, 5)
        upload_sizer = wx.GridSizer(0, 2, 0, 0)
        username_label = wx.StaticText(self.login_panel, wx.ID_ANY, "Username:", style=wx.ALIGN_RIGHT)
        username_label.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Segoe UI"))
        password_sizer.Add(username_label, 0, wx.ALIGN_BOTTOM | wx.EXPAND, 0)
        password_sizer.Add(self.username_textbox, 0, wx.ALIGN_BOTTOM, 0)
        password_sizer.AddGrowableRow(0)
        password_sizer.AddGrowableCol(0)
        login_grid_sizer.Add(password_sizer, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        password_label = wx.StaticText(self.login_panel, wx.ID_ANY, "Password:", style=wx.ALIGN_RIGHT)
        password_label.SetMinSize((74, 23))
        password_label.SetFont(wx.Font(12, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, "Segoe UI"))
        username_sizer.Add(password_label, 0, wx.ALIGN_BOTTOM | wx.ALIGN_RIGHT | wx.EXPAND, 0)
        username_sizer.Add(self.password_textbox, 0, 0, 0)
        username_sizer.AddGrowableRow(0)
        username_sizer.AddGrowableCol(0)
        login_grid_sizer.Add(username_sizer, 1, wx.ALIGN_CENTER_HORIZONTAL, 0)
        login_grid_sizer.Add(self.login_btn, 0, wx.EXPAND, 0)
        login_grid_sizer.AddGrowableCol(0)
        login_sizer.Add(login_grid_sizer, 1, 0, 0)
        upload_sizer.Add(self.upload_btn, 0, wx.EXPAND, 0)
        upload_sizer.Add(self.watch_btn, 0, wx.EXPAND, 0)
        self.upload_panel.SetSizer(upload_sizer)
        self.login_panel.SetSizer(login_sizer)
        self.spire_notebook.AddPage(self.login_panel, "Login")
        self.spire_notebook.AddPage(self.upload_panel, "Upload")
        main_sizer.Add(self.spire_notebook, 1, wx.EXPAND, 0)
        self.SetSizer(main_sizer)
        self.Layout()
        self.Centre()
        # end wxGlade


# end of class SpireUploaderFrame


class SpireLogUploaderGUI(wx.App):
    def OnInit(self):
        self.spire_frame = SpireUploaderFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.spire_frame)
        self.spire_frame.Show()
        if not spire_uploader.config.correct_config():
            self.spire_frame.incorrect_config_dialog.show_dialog()
        return True

# end of class SpireLogUploader

def main():
    spire_uploader_gui = SpireLogUploaderGUI(0)
    spire_uploader_gui.MainLoop()


if __name__ == "__main__":
    main()
